name: Deploy to AWS (SAM)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
      - name: Build
        run: sam build --template-file infra/template.yaml
      - name: Deploy
        run: sam deploy --stack-name app-trocas-celular --no-confirm-changeset --capabilities CAPABILITY_NAMED_IAM
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}